// Code generated by goctl. DO NOT EDIT.
package types

type OrderReq struct {
	Id   string `path:"id"`
	//Name string `path:"name"`
}

type OrderReply struct {
	Id     string `json:"id"`
	Name   string `json:"name"`
	//Status string `json:"status"`
}
